# Generated by Django 3.1.7 on 2021-11-13 06:43

import datetime
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Untitled', max_length=60)),
                ('study_type', models.CharField(blank=True, choices=[('FULL_TIME', 'FULL_TIME'), ('PART_TIME', 'PART_TIME')], default='FULL_TIME', max_length=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('capacity', models.CharField(max_length=4)),
                ('room_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('LECTURE', 'LECTURE'), ('LABORATORY', 'LABORATORY'), ('PROJECT', 'PROJECT'), ('SPORT_HALL', 'SPORT_HALL')], max_length=20), default=['LECTURE'], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('courses', models.ManyToManyField(to='api.Course')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldofstudy')),
                ('students', models.ManyToManyField(blank=True, to='api.Student')),
            ],
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='students',
            field=models.ManyToManyField(to='api.Student'),
        ),
        migrations.CreateModel(
            name='ECTSCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='api.Course')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldofstudy')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('course_type', models.CharField(choices=[('LECTURE', 'LECTURE'), ('LABORATORY', 'LABORATORY'), ('PROJECT', 'PROJECT')], default='LECTURE', max_length=15)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffaccount')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.courseinstructorinfo'),
        ),
    ]
