# Generated by Django 3.1.7 on 2021-10-25 08:17

import datetime
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20211003_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('class_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Project', 'Project'), ('Practicals', 'Practicals')], default='Lecture', max_length=45)),
                ('points_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('instructors', models.ManyToManyField(to='accounts.StaffAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('capacity', models.CharField(max_length=4)),
                ('room_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('LECTURE', 'LECTURE'), ('LABORATORY', 'LABORATORY'), ('PROJECT', 'PROJECT'), ('SPORT_HALL', 'SPORT_HALL')], max_length=20), default=['LECTURE'], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Untitled', max_length=60)),
                ('study_type', models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Part time', 'Part time')], default='Full time', max_length=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('students', models.ManyToManyField(to='api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ECTSCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('courses', models.ManyToManyField(to='api.Course')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldofstudy')),
            ],
        ),
    ]
