# Generated by Django 3.1.7 on 2021-10-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.staffaccount')),
                ('name', models.CharField(max_length=20)),
                ('surename', models.CharField(max_length=30)),
                ('institut', models.CharField(max_length=100)),
                ('jobTitle', models.CharField(max_length=50)),
                ('academic_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'LECTURE'), (2, 'LABORATORY'), (3, 'PROJECT'), (4, 'SPORT_HALL')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('index', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('surename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'STATIONARY'), (2, 'NOSTATIONARY')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('capacity', models.CharField(max_length=4)),
                ('roomType', models.ManyToManyField(to='api.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('students', models.ManyToManyField(blank=True, to='api.Student')),
                ('studyType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.studytype')),
            ],
        ),
    ]
