# Generated by Django 3.1.7 on 2021-10-03 16:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211003_1654'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('class_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Project', 'Project'), ('Practicals', 'Practicals')], default='Lecture', max_length=45)),
                ('points_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('instructors', models.ManyToManyField(to='accounts.StaffAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ECTSCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('courses', models.ManyToManyField(to='api.Course')),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='roomType',
            new_name='room_type',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='surename',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='studyType',
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='study_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], default='Full time', max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='StudyType',
        ),
        migrations.AddField(
            model_name='ectscard',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldofstudy'),
        ),
    ]
