# Generated by Django 3.1.7 on 2021-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211003_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='name',
            field=models.CharField(default='Untitled', max_length=60),
        ),
    ]
