# Generated by Django 3.1.7 on 2021-11-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211121_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableunit',
            name='field_groups',
            field=models.ManyToManyField(to='api.FieldGroup'),
        ),
    ]
