# Generated by Django 3.1.7 on 2021-10-04 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fieldofstudy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
