# Generated by Django 3.1.7 on 2021-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_timetableunit_field_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_instructor_info',
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor_info',
            field=models.ManyToManyField(to='api.CourseInstructorInfo'),
        ),
    ]
