# Generated by Django 3.1.7 on 2021-11-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211003_1654'),
        ('api', '0003_auto_20211025_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='ectscard',
            name='year',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('courses', models.ManyToManyField(to='api.Course')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldofstudy')),
                ('students', models.ManyToManyField(blank=True, to='api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('LECTURE', 'LECTURE'), ('LABORATORY', 'LABORATORY'), ('PROJECT', 'PROJECT')], default='LECTURE', max_length=15)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffaccount')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.courseinstructorinfo'),
        ),
        migrations.AlterField(
            model_name='ectscard',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester'),
        ),
    ]
