# Generated by Django 3.1.7 on 2021-11-07 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211106_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hours',
        ),
        migrations.AddField(
            model_name='courseinstructorinfo',
            name='hours',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
            preserve_default=False,
        ),
    ]
