# Generated by Django 3.1.7 on 2021-10-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211006_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='students',
            field=models.ManyToManyField(to='api.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
