# Generated by Django 3.1.7 on 2021-11-07 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211107_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructorinfo',
            name='hours',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
