# Generated by Django 3.1.7 on 2021-10-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211006_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='name',
            field=models.CharField(blank=True, default='Untitled', max_length=60),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='study_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Part time', 'Part time')], default='Full time', max_length=10),
        ),
    ]
