# Generated by Django 3.1.7 on 2021-10-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211006_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
