# Generated by Django 3.1.7 on 2021-11-27 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211127_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='balance_of_work_of_an_avg_student',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_of_the_subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='didactic_methods',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='literature',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='methods_of_verification_of_learning_outcomes_and_criteria',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='purposes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject_learning_outcomes',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='semester_end_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 27, 18, 35, 21, 216191)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='semester_start_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 27, 18, 35, 21, 216178)),
        ),
        migrations.AlterField(
            model_name='timetableunit',
            name='end_hour',
            field=models.TimeField(default=datetime.datetime(2021, 11, 27, 18, 35, 21, 215228)),
        ),
        migrations.AlterField(
            model_name='timetableunit',
            name='start_hour',
            field=models.TimeField(default=datetime.datetime(2021, 11, 27, 18, 35, 21, 215211)),
        ),
    ]
