# Generated by Django 3.1.7 on 2021-10-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211009_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
