# Generated by Django 3.1.7 on 2021-10-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211009_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='ectscard',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
