# Generated by Django 3.1.7 on 2021-12-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211215_1146'),
        ('api', '0014_auto_20211214_2036'),
    ]

    operations = [
    ]
