# Generated by Django 3.1.7 on 2021-12-19 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20211219_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_instructor_info',
        ),
        migrations.AddField(
            model_name='courseinstructorinfo',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_end_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 19, 10, 35, 3, 639654)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_start_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 19, 10, 35, 3, 639637)),
        ),
        migrations.AlterField(
            model_name='timetableunit',
            name='end_hour',
            field=models.TimeField(default=datetime.datetime(2021, 12, 19, 10, 35, 3, 643284)),
        ),
        migrations.AlterField(
            model_name='timetableunit',
            name='start_hour',
            field=models.TimeField(default=datetime.datetime(2021, 12, 19, 10, 35, 3, 643266)),
        ),
    ]
