# Generated by Django 3.1.7 on 2021-12-25 10:17

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211223_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LECTURE', 'LECTURE'), ('LABORATORY', 'LABORATORY'), ('PROJECT', 'PROJECT'), ('SPORT_HALL', 'SPORT_HALL')], max_length=37),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_end_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 25, 10, 17, 27, 414601)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_start_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 25, 10, 17, 27, 414583)),
        ),
        migrations.AlterField(
            model_name='timetableunit',
            name='end_hour',
            field=models.TimeField(default=datetime.datetime(2021, 12, 25, 10, 17, 27, 418211)),
        ),
        migrations.AlterField(
            model_name='timetableunit',
            name='start_hour',
            field=models.TimeField(default=datetime.datetime(2021, 12, 25, 10, 17, 27, 418195)),
        ),
    ]
