# Generated by Django 3.1.7 on 2021-12-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211224_2146'),
        ('api', '0020_auto_20211225_1028'),
    ]

    operations = [
    ]
