# Generated by Django 3.1.7 on 2021-12-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20211230_1903'),
        ('api', '0014_auto_20211214_1952'),
    ]

    operations = [
    ]
