# Generated by Django 3.1.7 on 2021-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='academic_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staffaccount',
            name='institute',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffaccount',
            name='job_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staffaccount',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='staffaccount',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
