# Generated by Django 3.1.7 on 2022-01-05 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='pensum_hours',
            field=models.IntegerField(default=168, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
