# Generated by Django 3.1.7 on 2022-01-17 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20220117_1851'),
        ('accounts', '0002_staffaccount_pensum_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffaccount',
            name='account',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='pensum_hours',
            field=models.IntegerField(blank=True, default=168, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='DeaneryAccount',
        ),
        migrations.DeleteModel(
            name='StaffAccount',
        ),
    ]
