# Generated by Django 3.1.7 on 2022-01-17 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220117_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pensum_hours',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
