from django.urls import path

from .views import (StudentGetPostView,
                    StudentRetrieveUpdateDeleteView,
                    RoomGetPostView,
                    RoomRetrieveUpdateDeleteView,
                    CourseInstructorInfoGetPostView,
                    CourseInstructorInfoRetrieveUpdateDeleteView,
                    CourseGetPostView,
                    CourseRetrieveUpdateDeleteView,
                    FieldOfStudyGetPostView,
                    FieldOfStudyRetrieveUpdateDeleteView,
                    SemesterRetrieveUpdateDeleteView,
                    SemesterGetPostView,
                    ECTSCardGetPostView,
                    ECTSCardRetrieveUpdateDeleteView,
                    FieldGroupGetPostView,
                    FieldGroupRetrieveUpdateDeleteView,
                    TimeTableUnitRetrieveUpdateDeleteView,
                    TimeTableUnitGetPostView,
                    TimeTableGetPostView,
                    TimeTableRetrieveUpdateDeleteView,
                    StudentsCSVExportView,
                    RoomsCSVExportView,
                    CourseCSVExportView,
                    SemesterCSVExportView,
                    FieldGroupCSVExportView,
                    FieldOfStudyCSVExportView,
                    ECTSCardCSVExportView,
                    TimeTableCSVExportView,
                    TimeTableUnitCSVExportView,
                    RoomCSVImportView,
                    CourseInstructorInfosCSVExportView,
                    CourseCSVImportView,
                    CourseInstructorInfosCSVImportView,
                    StudentsCSVImportView,
                    SemesterCSVImportView,
                    FieldGroupCSVImportView,
                    FieldOfStudyCSVImportView,
                    ECTSCardCSVImportView,
                    TimeTableUnitCSVImportView,
                    TimeTableCSVImportView,
                    StudentsJSONExportView,
                    CourseJSONExportView,
                    RoomsJSONExportView,
                    CourseInstructorInfosJSONExportView,
                    SemesterJSONExportView,
                    FieldGroupJSONExportView,
                    FieldOfStudyJSONExportView,
                    TimeTableUnitJSONExportView,
                    TimeTableJSONExportView,
                    ECTSCardJSONExportView,
                    StudentsJSONImportView, RoomJSONImportView, CourseJSONImportView,
                    CourseInstructorInfosJSONImportView,
                    SemesterJSONImportView, FieldGroupJSONImportView,
                    FieldOfStudyJSONImportView, TimeTableJSONImportView,
                    TimeTableUnitJSONImportView, ECTSCardJSONImportView,
                    TimeTableWithTimeTableUnitsPostView, AddTimeTableUnitToTimeTable,
                    StaffJSONExportView, AvailableRoomsView, UpdateTimeTableUnit
                    )

urlpatterns = [
    path('students', StudentGetPostView.as_view(), name='student_get_post'),
    path('students/export/csv', StudentsCSVExportView.as_view(), name='export-csv-students'),
    path('students/export/json', StudentsJSONExportView.as_view(), name='export-json-students'),
    path('students/import/csv', StudentsCSVImportView.as_view(), name='import-csv-students'),
    path('students/import/json', StudentsJSONImportView.as_view(), name='import-json-students'),
    path('students/<int:pk>', StudentRetrieveUpdateDeleteView.as_view(), name='student_update_delete'),
    path('courseinstructorinfo', CourseInstructorInfoGetPostView.as_view(), name='courseinstructorinfo_get_post'),
    path('courseinstructorinfo/<int:pk>', CourseInstructorInfoRetrieveUpdateDeleteView.as_view(),
         name='courseinstructorinfo_update_delete'),
    path('courseinstructorinfo/export/csv', CourseInstructorInfosCSVExportView.as_view(),
         name='export-csv-courseinstructorinfo'),
    path('courseinstructorinfo/export/json', CourseInstructorInfosJSONExportView.as_view(),
         name='export-json-courseinstructorinfo'),
    path('courseinstructorinfo/import/csv', CourseInstructorInfosCSVImportView.as_view(),
         name='import-csv-courseinstructorinfo'),
    path('courseinstructorinfo/import/json', CourseInstructorInfosJSONImportView.as_view(),
         name='import-json-courseinstructorinfo'),
    path('course', CourseGetPostView.as_view(), name='course_get_post'),
    path('course/<int:pk>', CourseRetrieveUpdateDeleteView.as_view(),
         name='course_update_delete'),
    path('course/export/csv', CourseCSVExportView.as_view(), name='export-csv-courses'),
    path('course/export/json', CourseJSONExportView.as_view(), name='export-json-courses'),
    path('course/import/csv', CourseCSVImportView.as_view(), name='import-csv-courses'),
    path('course/import/json', CourseJSONImportView.as_view(), name='import-json-courses'),
    path('rooms', RoomGetPostView.as_view(), name='room_get_post'),
    path('rooms/<int:pk>', RoomRetrieveUpdateDeleteView.as_view(), name='room_update_delete'),
    path('rooms/export/csv', RoomsCSVExportView.as_view(), name='export-csv-rooms'),
    path('rooms/export/json', RoomsJSONExportView.as_view(), name='export-json-rooms'),
    path('rooms/import/csv', RoomCSVImportView.as_view(), name='import-csv-room'),
    path('rooms/import/json', RoomJSONImportView.as_view(), name='import-json-room'),
    path('fieldofstudy', FieldOfStudyGetPostView.as_view(), name='fieldofstudy_get_post'),
    path('fieldofstudy/<int:pk>', FieldOfStudyRetrieveUpdateDeleteView.as_view(), name='fieldofstudy_update_delete'),
    path('fieldofstudy/export/csv', FieldOfStudyCSVExportView.as_view(), name='export-csv-fieldofstudy'),
    path('fieldofstudy/export/json', FieldOfStudyJSONExportView.as_view(), name='export-json-fieldofstudy'),
    path('fieldofstudy/import/csv', FieldOfStudyCSVImportView.as_view(), name='import-csv-fieldofstudy'),
    path('fieldofstudy/import/json', FieldOfStudyJSONImportView.as_view(), name='import-json-fieldofstudy'),
    path('semester', SemesterGetPostView.as_view(), name='semester_get_post'),
    path('semester/<int:pk>', SemesterRetrieveUpdateDeleteView.as_view(), name='semester_update_delete'),
    path('semester/export/csv', SemesterCSVExportView.as_view(), name='export-csv-semesters'),
    path('semester/export/json', SemesterJSONExportView.as_view(), name='export-json-semesters'),
    path('semester/import/csv', SemesterCSVImportView.as_view(), name='import-csv-semesters'),
    path('semester/import/json', SemesterJSONImportView.as_view(), name='import-json-semesters'),
    path('ectscard', ECTSCardGetPostView.as_view(), name='ectscard_get_post'),
    path('ectscard/<int:pk>', ECTSCardRetrieveUpdateDeleteView.as_view(), name='ectscard_update_delete'),
    path('ectscard/export/csv', ECTSCardCSVExportView.as_view(), name='export-csv-ectscard'),
    path('ectscard/export/json', ECTSCardJSONExportView.as_view(), name='export-json-ectscard'),
    path('ectscard/import/csv', ECTSCardCSVImportView.as_view(), name='import-csv-ectscard'),
    path('ectscard/import/json', ECTSCardJSONImportView.as_view(), name='import-json-ectscard'),
    path('fieldgroup', FieldGroupGetPostView.as_view(), name='field_group_get_post'),
    path('fieldgroup/<int:pk>', FieldGroupRetrieveUpdateDeleteView.as_view(), name='field_group_update_delete'),
    path('fieldgroup/export/csv', FieldGroupCSVExportView.as_view(), name='export-csv-fieldgroup'),
    path('fieldgroup/export/json', FieldGroupJSONExportView.as_view(), name='export-json-fieldgroup'),
    path('fieldgroup/import/csv', FieldGroupCSVImportView.as_view(), name='import-csv-fieldgroup'),
    path('fieldgroup/import/json', FieldGroupJSONImportView.as_view(), name='import-json-fieldgroup'),
    path('timetable', TimeTableGetPostView.as_view(), name='timetable_get_post'),
    path('timetable/<int:pk>', TimeTableRetrieveUpdateDeleteView.as_view(), name='timetable_update_delete'),
    path('timetable/export/csv', TimeTableCSVExportView.as_view(), name='export-csv-timetable'),
    path('timetable/export/json', TimeTableJSONExportView.as_view(), name='export-json-timetable'),
    path('timetable/import/csv', TimeTableCSVImportView.as_view(), name='import-csv-timetable'),
    path('timetable/import/json', TimeTableJSONImportView.as_view(), name='import-json-timetable'),
    path('timetableunit', TimeTableUnitGetPostView.as_view(), name='timetableunit_get_post'),
    path('timetableunit/<int:pk>', TimeTableUnitRetrieveUpdateDeleteView.as_view(), name='timetableunit_update_delete'),
    path('timetableunit/export/csv', TimeTableUnitCSVExportView.as_view(), name='export-csv-timetableunit'),
    path('timetableunit/export/json', TimeTableUnitJSONExportView.as_view(), name='export-json-timetableunit'),
    path('timetableunit/import/csv', TimeTableUnitCSVImportView.as_view(), name='import-csv-timetableunit'),
    path('timetableunit/import/json', TimeTableUnitJSONImportView.as_view(), name='import-json-timetableunit'),
    path('timetablewithtimetableunits', TimeTableWithTimeTableUnitsPostView.as_view(), name='timetablewith-ttunits-post'),
    path('timetable/<int:pk>/timetableunit', AddTimeTableUnitToTimeTable.as_view(), name='add-ttunit-to-timetable'),
    path('timetable/<int:timetable_pk>/timetableunit/<int:timetableunit_pk>', UpdateTimeTableUnit.as_view(), name='ipdate-ttunit'),
    path('staff/export/json', StaffJSONExportView.as_view(), name='import-json-staff'),
]
