version: "3"
services:

  django:
    build: ./backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es

  db:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      
  es:
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"